Documento de visao
fga-eps-mds/2021-1-Bot pull request #122
Opened 2021-09-02 02:32 UTC by Thais-ra

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Documentação atualizada
- [ ] Novo arquivo (mundança que adiciona funcionabilidade)
- [ ] Correção de bug (mudança que **NÃO** muda funcionabilidade)
- [ ] Mudança decisiva no arquivo (correção ou recurso que faz com que funcionabilidade existente seja alterada)
- [ ] "Não sei dizer o que mudou, mas nada está igual" (Victor & Leo)

### Descrição
Criação do documento de visão.

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| [#87](https://github.com/fga-eps-mds/2021-1-Bot/issues/87) | Criação do documento de visão |

## Lista de controle:
- [x] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [x] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [x] Todos os membros estão de acordo com a atualização

2021-09-07 15:29 UTC, PedroLSF approved these changes

2021-09-09 15:48 UTC, gatotabaco requested changes

2021-09-09 15:48 UTC, gatotabaco commented on docs/documento-de-visao.md
> +Esse projeto tem como objetivo desenvolver um bot com 3 temas com a finalidade de solucionar as diversas dúvidas que surgiram durante a pandemia do Coronavírus, disponibilizando informações sobre vac
"Esse projeto tem como objetivo desenvolver um bot com 3 temas com a finalidade de solucionar as diversas dúvidas que surgiram durante a pandemia[...]" poderia ser modificado para:

Esse projeto tem como objetivo o desenvolvimento de um bot com 3 temas, cuja principal finalidade é a de solucionar diversas dúvidas que surgem entre a população acerca da COVID-19

"políticas pública" tem que estar no plural, escrito como "políticas públicas".

2021-09-09 15:48 UTC, gatotabaco commented on docs/documento-de-visao.md
> +| Pessoas físicas interessadas por informações | Pessoas que querem informações sobre covid ou que querem ser alertadas sobre novidades relacionadas ao tema |  Usuários desinformados  | Além de utili
trocar "reconhedimento" para reconhecimento

2021-09-09 15:48 UTC, gatotabaco commented on docs/documento-de-visao.md
> +As capacidades do produto vão de encontro com as necessidades do público em geral que tem anseio por informações fáceis, atuais e verídicas sobre o CoronaVírus e pessoas físicas que ainda nao possuem
"pessoas físicas que ainda nao possuem" falta o til no não.

substituir "incluindo informações sobre as novas pesquisas sobre as vacinas." por:

incluindo informações de novas pesquisas sobre as vacinas.

2021-09-09 15:48 UTC, gatotabaco commented on docs/documento-de-visao.md
> +O bot carrega informações de prevenção e cuidados no geral, além de tirar dúvidas mais frequêntes a respeito das vacinas aprovadas pela ANVISA.
frequentes está escrito errado

2021-09-09 15:48 UTC, gatotabaco commented on docs/documento-de-visao.md
> +O bot trás dicas de home office, saúde mental, além de atualizar o usuário com novidades sobre descobertas e casos de covid.
trás está utilizado de maneira errada. Nesse caso é traz, que é uma conjuração do verbo "trazer".

2021-09-10 18:23 UTC, gatotabaco approved these changes

2021-09-11 18:11 UTC, gatotabaco approved these changes

2021-09-11 22:33 UTC, merged