Backlog do produto
fga-eps-mds/2021-1-Bot pull request #123
Opened 2021-09-02 15:49 UTC by Thais-ra

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Documentação atualizada
- [ ] Novo arquivo (mundança que adiciona funcionabilidade)
- [ ] Correção de bug (mudança que **NÃO** muda funcionabilidade)
- [ ] Mudança decisiva no arquivo (correção ou recurso que faz com que funcionabilidade existente seja alterada)
- [ ] "Não sei dizer o que mudou, mas nada está igual" (Victor & Leo)

### Descrição
Criação da primeira versão do backlog do produto.

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| [#65](https://github.com/fga-eps-mds/2021-1-Bot/issues/65) | Backlog versão inicial |
       

## Lista de controle:
- [x] Você vereficou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [x] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [ ] Todos os membros estão de acordo com a atualização

2021-09-02 20:46 UTC, matheusakio approved these changes

2021-09-02 21:17 UTC, PedroLSF requested changes

2021-09-02 21:17 UTC, PedroLSF commented on docs/documento-de-backlog.md
> +|US11|Eu, como usuário, desejo saber sobre os sintomas da covid|Must|
Falta o US12

2021-09-02 21:17 UTC, PedroLSF commented on docs/documento-de-backlog.md
> +|----------|-----------|---------|
Falta a US14

2021-09-02 21:17 UTC, PedroLSF commented on docs/documento-de-backlog.md
> +|US28|Eu, como usuário, desejo saber qual a quantidade de vacinados na minha cidade/país|Could|
US279 está errado, seria US29

2021-09-02 21:17 UTC, PedroLSF commented on docs/documento-de-backlog.md
> +|----------|-----------|---------|
US14: Eu, como usuário, desejo saber qual a quantidade de mortos por covid na minha cidade/país

2021-09-02 21:27 UTC, PedroLSF requested changes
Olhar a pontuação e levantar debates para a verificação

2021-09-02 21:29 UTC, PedroLSF requested changes
Olhem as US e o levantamento dos pontos.

2021-09-02 21:29 UTC, PedroLSF commented on docs/documento-de-backlog.md
> +|US11|Eu, como usuário, desejo saber sobre os sintomas da covid|Must| 3 |
Falta a US12

2021-09-02 21:29 UTC, PedroLSF commented on docs/documento-de-backlog.md
> +|US13|Eu, como usuário, desejo saber qual a quantidade de infectados por covid na minha cidade/país|Should| 13 |
Falta a US14
US14: Eu, como usuário, desejo saber qual a quantidade de mortos por covid na minha cidade/país

2021-09-02 21:29 UTC, PedroLSF commented on docs/documento-de-backlog.md
> +|US279|Eu, como usuário, desejo saber quando posso me vacinar|Must| 5 |
US279 está errado, seria US29

2021-09-02 21:31 UTC, AmandaNbr approved these changes
Após as acrescentar mudanças que o @PedroLSF sugeriu acredito que o documento estará perfeito.

2021-09-05 22:37 UTC, gatotabaco reviewed
Apenas uma correção relativa a um possível erro de concordancia

2021-09-05 22:37 UTC, gatotabaco commented on docs/documento-de-backlog.md
> +|Features|Features é semelhante a Epics, porém é mais detalhada em relação ao que é sua função|
|Features|Features são semelhantes a Epics, porém são mais detalhadas em relação a sua função|

2021-09-09 14:28 UTC, gatotabaco requested changes
Na definição das Features as duas orações devem estar no plural

2021-09-09 14:28 UTC, gatotabaco commented on docs/documento-de-backlog.md
> +|Features|Features são semelhante a Epics, porém é mais detalhada em relação ao que é sua função|
Falta corrigir o erro de concordância na segunda oração

|Features|Features são semelhante a Epics, porém são mais detalhadas em relação ao que é a sua função|

2021-09-09 15:17 UTC, gatotabaco approved these changes

2021-09-09 19:17 UTC, PedroLSF approved these changes

2021-09-09 19:17 UTC, merged