Documentation/(#137)documento de devops
fga-eps-mds/2021-1-Bot pull request #138
Opened 2021-09-03 23:50 UTC by yudi-azvd

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Documentação atualizada

### Descrição
Foi adicionado um documento markdown para a documentação de Devops. Atualmente contém apenas uma versão inicial do Roadmap de Devops.

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #137 | Documentação de evolução de Devops |

2021-09-03 23:54 UTC, yudi-azvd commented
Não tá pronto ainda kkk vide imagem 

![image](https://user-images.githubusercontent.com/37981839/132075170-beb7cf4d-ffb8-4d6f-9e1e-fa3467afe5b2.png)

2021-09-05 22:51 UTC, gatotabaco requested changes

2021-09-05 22:51 UTC, gatotabaco commented on docs/documento-de-devops.md
> +<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQqGRTgDVmQxrsq90kGuEbR-3erJeX67kQgF4UB9D0BE5dASLXsTxJ8mwxVmhef9wZeX59WkRvRELGj/pubhtml?widget=true&amp;headers=false" width="900px" heigh
não é possível visualizar o roadmap apenas pelo arquivo. É necessário clicar no link (era pra ser assim?)

2021-09-05 22:53 UTC, gatotabaco commented
> Não tá pronto ainda kkk vide a imagem. Mas acho que não foi feito pra redenrizar no github, mas pelo gerador de HTML do gerador de documentação.
> 
> ![image](https://user-images.githubusercontent.com/37981839/132075170-beb7cf4d-ffb8-4d6f-9e1e-fa3467afe5b2.png)

A intenção é enviar o documento sem essa parte pronta? Se sim, então retiro meu apontamento sobre necessidade de mudança.

2021-09-06 11:52 UTC, yudi-azvd commented on docs/documento-de-devops.md
> +<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQqGRTgDVmQxrsq90kGuEbR-3erJeX67kQgF4UB9D0BE5dASLXsTxJ8mwxVmhef9wZeX59WkRvRELGj/pubhtml?widget=true&amp;headers=false" width="900px" heigh
acho que isso é pra ser visualizado apenas nas páginas de documentação.

2021-09-06 21:53 UTC, gatotabaco commented on docs/documento-de-devops.md
> +<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQqGRTgDVmQxrsq90kGuEbR-3erJeX67kQgF4UB9D0BE5dASLXsTxJ8mwxVmhef9wZeX59WkRvRELGj/pubhtml?widget=true&amp;headers=false" width="900px" heigh
Entendi. Vou aprovar aqui então

2021-09-06 21:55 UTC, gatotabaco approved these changes
Pra além do roadmap com aparencia ¨quebrada¨, tudo certo.

2021-09-09 14:04 UTC, Thais-ra commented
@gatotabaco, parece q é normal mesmo para a inserção de tabelas. Olhei um exemplo no repositório lendit q o documento no git ta assim:
![image](https://user-images.githubusercontent.com/35047444/132700122-3746ad4c-c80f-4d77-b0de-d9c5c801b32d.png)
Mas no git pages ela fica renderizada direitinho:
![image](https://user-images.githubusercontent.com/35047444/132700602-5933ed65-c0f0-4184-af22-2edc3211f57a.png)

2021-09-09 14:06 UTC, merged