Documentation#154/roadmap
fga-eps-mds/2021-1-Bot pull request #172
Opened 2021-09-10 17:40 UTC by PedroLSF

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Documentação atualizada

### Descrição
Foi feito um roadmap inicial com relação as 6 primeiras sprints

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #154| Roadmap |
      

## Lista de controle:
- [ ] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [ ] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [ ] Todos os membros estão de acordo com a atualização

2021-09-10 18:19 UTC, gatotabaco approved these changes

2021-09-10 22:25 UTC, AmandaNbr requested changes

2021-09-10 22:25 UTC, AmandaNbr commented on docs/roadmap.md
> +# Roadmap do Porduto
Produto escrito errado.

2021-09-11 21:14 UTC, HenriqueHida approved these changes

2021-09-11 22:00 UTC, gatotabaco approved these changes

2021-09-11 22:26 UTC, AmandaNbr approved these changes

2021-09-11 22:27 UTC, merged