Documentation#165/gerencia sprint5
fga-eps-mds/2021-1-Bot pull request #187
Opened 2021-09-12 00:43 UTC by gatotabaco

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Documentação atualizada

### Descrição
Gerencia sprint 5

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #165  | Documentação da sprint 5 |
      
## Lista de controle:
- [x] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [x] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [x] Todos os membros estão de acordo com a atualização

## Quem contribuiu?
@gatotabaco

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite requested changes

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/planejamento.md
> +| 11/09/2021 |    0.2   | Envio inicial do documento de planejamento da sprint 4 | [Matheus Sousa](https://github.com/https://github.com/gatotabaco)|
Tem que haver a troca da descrição do que foi alterado.

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/planejamento.md
> +| [#65](https://github.com/fga-eps-mds/2021-1-Bot/issues/65) | Backlog versão inicial | 5 | Thais e Ana |
Falta adicionar o Pedro, não?

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/planejamento.md
> +## Papeis
Papéis(acento)

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +Após isso, na reunião com os tecnologistas foi decidido o mvp do bot para
Trocar o nome do bot para chatbot ( deixar padronizado)

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +a release 1: um bot dentro de um container que irá responder algumas perguntas básicas (ainda não acessando nenhuma API).
Trocar bot para chatbot

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +Nessa Sprint foram trabalhados e(ou) concluídos(ou melhorados) os documentos de arquitetura, criação e formatação do GHPages, termo de abertura,
'os' não dos

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +política de branch, estrutura Analítica e protótipo de baixa fidelidade, sendo que este último já estava quase concluído na sprint passada, faltando apenas um membro do
Letra maiúscula no estrutura

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +grupo fazer, e pode ser visto na [Issue](https://github.com/fga-eps-mds/2021-1-Bot/issues/31) relativa a esta questão.
é na issue ou no problema?

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +O Scrum Master teve problemas para concluir as documentações pendentes, que ficaram como dívida para a próxima sprint em conjunto com o backlog, a elicitação de requisitos,
Trocar "como" para com e tirar a vírgula depois de pendentes pois o 'que' representa essa junção de uma oração a outra.

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +A daily dessa sprint foi feita e pode ser vista aqui: [Daily Sprint 4.pdf](https://github.com/fga-eps-mds/2021-1-Bot/files/7148541/Daily.Sprint.4.pdf)
É uma ou um?
Poderia ser escrito como: "Uma dessas sprints diárias foi feita e pode ser vista aqui:(link)"

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +| Data       | Versão | Descrição                      | Autor             |
Troca dados por data
Adiciona uma barra e espaço depois de descrição e antes de autor

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +| 11/09/2021 |  0.1   | Versão inicial | [Matheus Sousa](https://github.com/gatotabaco)|
Data esta errada, não seria 11/09/2021?
Troca o ',' (vírgula) para '.' (ponto) no número da versão.

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +além das reuniões de daily. Alguns dos membros tiveram imprevistos e emergencias nessa sprint, o que afetou a produtividade.
Tirar o "de" depois de reuniões

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/planejamento.md
> +como o de visao e como contribuir (no readme). Além disso, temos um punhado de dívidas alocadas de tarefas que foram cumpridas parcialmente ou que ainda nao tinham prontos os requisitos
- Falta o til no "visão"
- Trocar a palavra "punhado" para muitas ou várias dívidas alocadas...
- Corrigir o "nao" sem acento para o não com acento
- Trocar 'prontos' para prontas
- Trocar essa parte "ainda nao estão prontos os requisitos para cumpridas." para " ainda não estão finalizadas para que cumpram com os requisitos planejados."

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/planejamento.md
> +| Data       | Versão | Descrição                      | Autor             |
- Corrigir a palavra "dados" para data.
- Espaçamento e | entre "Descrição e Autor"

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/planejamento.md
> +| 11/09/2021 |    0.1   | Envio inicial do documento de planejamento da sprint 5 | [Matheus Sousa](https://github.com/https://github.com/gatotabaco)|
- Correção de data para 11/09/2021
- Correção da vírgula no número da versão para o ponto

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/planejamento.md
> +## Papeis
Corrigir papeis com acento

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +Nessa sprint novamente foram acumuladas as documentações de gerencia.
Corrigir "Nessa sprint novamente foram acumuladas como documentações de gerencia." para " Nessa sprint novamente foram acumuladas as documentações de gerencia."

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +A [versão inicial do backlog](https://github.com/fga-eps-mds/2021-1-Bot/blob/main/docs/documento-de-backlog.md) foi concluída, assim como a elicitação dos requisitos. Além disso, as perguntas sobre v
Corrigir o 'do' de: a parte (do) para 'de'

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +Tudo isso foi possível graças às reuniões que estão ocorrendo entre Scrum Masters e PO`s no início das sprints. Isso permite uma colaboração entre os membros de todos os grupos
Trocar o ` do PO`s para PO´s

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +| Data       | Versão | Descrição                      | Autor             |
- Corrigir a palavra "dados" para data.
- Espaçamento e | entre "Descrição e Autor"

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +| 11/09/2021 |  0.1   | Versão inicial | [Matheus Sousa](https://github.com/gatotabaco)|
- Correção de dados para 11/09/2021
- Correção da vírgula sem número da versão para o ponto

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +3. Os times estão se alinhando, mais rostinhos trabalhando e menos sobrecarga
-  os mais rostinhos trabalhando e menos sobrecarga - O que você quis dizer com 'rostinhos'? Acredito que tenha como melhorar.

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +2. Priorizar melhor as atividades, tentar deixar o minimo de tarefas possivel para o último dia da sprint
Correção de possível para possíveis

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +no que se refere a resolução das issues pendentes e elaboração de novas. Tivemos algumas falhas de comunicação, mas esse tipo de problema está ficando cada vez menos comum
Novas o que? Ficou estranho!

2021-09-12 01:54 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +devido a melhora nos canais de comunicaçao entre os grupos. A comunicação apenas por telegram não é efetiva e, por isso, as reuniões que acontecem são efetivas em
Corrigir o telegrama para telegram

2021-09-12 03:29 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint4/planejamento.md
> +| [#65](https://github.com/fga-eps-mds/2021-1-Bot/issues/65) | Backlog versão inicial | 5 | Thais e Ana |
@AnaCarolinaRodriguesLeite 

Nos responsáveis eu tô colocando sempre pessoas do nosso grupo que estão envolvidas nas issues

2021-09-12 03:38 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint4/resultados.md
> +Nessa Sprint foram trabalhados e(ou) concluídos(ou melhorados) os documentos de arquitetura, criação e formatação do GHPages, termo de abertura,
Não achei esse "dos"

2021-09-12 03:39 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint4/resultados.md
> +grupo fazer, e pode ser visto na [Issue](https://github.com/fga-eps-mds/2021-1-Bot/issues/31) relativa a esta questão.
É na issue mesmo. Ali é umm link para a issue em que estão os protótipos de baixa fidelidade

2021-09-12 03:43 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint4/resultados.md
> +A daily dessa sprint foi feita e pode ser vista aqui: [Daily Sprint 4.pdf](https://github.com/fga-eps-mds/2021-1-Bot/files/7148541/Daily.Sprint.4.pdf)
Não entendi esse! Esse link trata-se de uma imagem das respostas das nossas dailys

2021-09-12 03:44 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint4/resultados.md
> +| Data       | Versão | Descrição                      | Autor             |
No meu está Data. Como assim barra e espaço?

2021-09-12 03:45 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint4/resultados.md
> +| 11/09/2021 |  0.1   | Versão inicial | [Matheus Sousa](https://github.com/gatotabaco)|
No meu está exatamente como vc descreveu

2021-09-12 03:49 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint5/resultados.md
> +Nessa sprint novamente foram acumuladas as documentações de gerencia.
Não entendi. O "Acumuladas como documentações de gerencia" não fica meio estranho?

2021-09-12 22:44 UTC, AnaCarolinaRodriguesLeite requested changes
Algumas ainda não foram resolvidas para mim! Ainda continua o erro!

2021-09-12 22:44 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/planejamento.md
> +| [#65](https://github.com/fga-eps-mds/2021-1-Bot/issues/65) | Backlog versão inicial | 5 | Thais e Ana |
Entendi!

2021-09-12 22:44 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +Nessa Sprint foram trabalhados e(ou) concluídos(ou melhorados) os documentos de arquitetura, criação e formatação do GHPages, termo de abertura,
Desconsidera, vi algo que não tinha nada haver!

2021-09-12 22:44 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +grupo fazer, e pode ser visto na [Issue](https://github.com/fga-eps-mds/2021-1-Bot/issues/31) relativa a esta questão.
Beleza

2021-09-12 22:44 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +A daily dessa sprint foi feita e pode ser vista aqui: [Daily Sprint 4.pdf](https://github.com/fga-eps-mds/2021-1-Bot/files/7148541/Daily.Sprint.4.pdf)
Desconsidera tbm!

2021-09-12 22:44 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +| Data       | Versão | Descrição                      | Autor             |
Tava com o nome errado de data e sem aquela barrinha de | descrição |, entende?

2021-09-12 22:56 UTC, AnaCarolinaRodriguesLeite requested changes
Muitas coisas que tinha corrigido eu percebi que foi um erro, então eu revi todas e algumas eu expliquei o motivo e outras eu apaguei por erro mesmo. Deixei apenas as que realmente são necessárias para serem alteradas. Desculpa!

2021-09-12 22:56 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +| Data       | Versão | Descrição                      | Autor             |
Acho que meu PC que traduziu e ficou diferente, PERDÃO!

2021-09-12 22:56 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint4/resultados.md
> +| 11/09/2021 |  0.1   | Versão inicial | [Matheus Sousa](https://github.com/gatotabaco)|
A mesma coisa da anterior, desconsidera, PERDÃO!

2021-09-12 22:56 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/planejamento.md
> +como o de visao e como contribuir (no readme). Além disso, temos um punhado de dívidas alocadas de tarefas que foram cumpridas parcialmente ou que ainda nao tinham prontos os requisitos
Foi alterado? Não vi alteração!

2021-09-12 22:56 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/planejamento.md
> +| Data       | Versão | Descrição                      | Autor             |
Desconsidera, porque foi o mesmo erro de tradução automática do PC, Perdão!

2021-09-12 22:56 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/planejamento.md
> +| 11/09/2021 |    0.1   | Envio inicial do documento de planejamento da sprint 5 | [Matheus Sousa](https://github.com/https://github.com/gatotabaco)|
Desconsidera, porque foi o mesmo erro de tradução automática do PC, Perdão!

2021-09-12 22:56 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +Nessa sprint novamente foram acumuladas as documentações de gerencia.
Relendo novamente, vejo que não necessita mexer, pode deixar do jeito que está! PERDÃO!

2021-09-12 22:56 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +3. Os times estão se alinhando, mais rostinhos trabalhando e menos sobrecarga
Deixe mais técnico, visto que é um documento de gerenciamento de atividades feitas.

2021-09-12 23:58 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint5/resultados.md
> +3. Os times estão se alinhando, mais rostinhos trabalhando e menos sobrecarga
Certo! Nessa parte eu apenas repliquei o que foi colocado pelos membros do grupo na planilha

2021-09-12 23:59 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint5/resultados.md
> +2. Priorizar melhor as atividades, tentar deixar o minimo de tarefas possivel para o último dia da sprint
Nesse caso acho que é possível mesmo porque se refere ao mínimo possível, e não tarefas possíveis

2021-09-13 00:13 UTC, AnaCarolinaRodriguesLeite requested changes

2021-09-13 00:13 UTC, AnaCarolinaRodriguesLeite commented on gerencia/TimeCapivara/sprint5/resultados.md
> +2. Priorizar melhor as atividades, tentar deixar o minimo de tarefas possivel para o último dia da sprint
É porque a palavra tarefa está no plural e com relação a concordância nominal, ficaria que digamos "mais" correto ao meu ver. Outra coisa que percebi é no comentário sobre a minha revisão você colocou a palavra mínimo com acento, mas no docs não esta com acento. kkkkk

2021-09-13 00:31 UTC, gatotabaco commented on gerencia/TimeCapivara/sprint5/resultados.md
> +2. Priorizar melhor as atividades, tentar deixar o minimo de tarefas possivel para o último dia da sprint
Que tal modificar para "Priorizar melhor as atividades, tentar deixar o mínimo possível de tarefas para o último dia da sprint"

2021-09-13 01:01 UTC, AnaCarolinaRodriguesLeite approved these changes

2021-09-13 01:14 UTC, merged