Documentation#182/correção documento de arquitetura
fga-eps-mds/2021-1-Bot pull request #199
Opened 2021-09-12 21:42 UTC by victorear05

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Documentação atualizada

### Descrição
A partir do feedback da revisão feita no documento de arquitetura, realizei as mudanças necessárias, fazendo assim alterações nos tópicos:
2. Representação Arquitetural
2.1 Tecnologias
4.2 Descrições de Casos de Uso
5 Visão Lógica

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #182 | Correção de erros no documento de arquitetura |

### Configuração de teste :

## Lista de controle:
- [x] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [x] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [ ] Todos os membros estão de acordo com a atualização

## Quem contribuiu?
@victorear05

2021-09-13 00:02 UTC, AnaCarolinaRodriguesLeite requested changes
Vi todo o documento e lhe dou os parabéns, ficou bom! Porém houve uma parte pela qual eu não consegui fazer um comentário, então eu deixo aqui a parte pelo qual pode haver uma pouca alteração e como deve ser a alteração,ok?
- Parte do texto que não consegui fazer comentário: "O projeto aqui apresentado trata-se de um Chat Bot integrado a plataforma Telegram e tem como função informar o usuário acerca de conteúdos sobre o COVID-19 com informações fornecidas, dentro outros, pelo site Corona Cidades, sobre como prevenir o contágio, gestão pública, e informações relacionadas à vacinação na região do usuário."
- Alteração a ser feita: "O projeto aqui apresentado trata-se de um _Chat Bot_(chatbot) integrado a plataforma Telegram e tem como função informar _o_(ao) usuário acerca _de_ (dos) conteúdos sobre _o_(a) COVID-19 com informações fornecidas, _dentro_(dentre) outros, pelo site Corona Cidades, sobre como prevenir o contágio, gestão pública, e informações relacionadas à vacinação na região do usuário.
- Os erros encontrados estão em itálico para diferenciar e a correção está logo a frente entre parêntesis.

2021-09-13 11:40 UTC, victorear05 commented on docs/documento-de-arquitetura.md
> +Para a construção do sistema usaremos o Rasa, um framework utilizado para construção de bot's de conversação. A escolha dele foi feita por ser uma alternativa open source, robusta e de fácil uso para
Obrigado :)

2021-09-13 11:46 UTC, victorear05 commented
Muito obrigado pelo elogio, pela revisão e feedback também, fiz as alterações e dei o commit/push. Daí se tiver tudo certinho eu dou o merge pra main.

2021-09-14 01:57 UTC, AnaCarolinaRodriguesLeite approved these changes

2021-09-14 03:00 UTC, merged