Inicio da nova versão do backlog
fga-eps-mds/2021-1-Bot pull request #249
Opened 2021-09-26 20:51 UTC by PedroLSF

## O que mudou?
Foi feita uma versão 2 do backlog

### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Novo arquivo (mundança que adiciona funcionabilidade)

### Descrição
Por favor, faça um resumo do que mudou e qual(is) issue(s) foi(ram) resolvida(s). Liste também todas as depedências necessárias para essa mudança.

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #230  | Alteração do Backlog |

      

## Lista de controle:
- [x] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [x] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [x] Todos os membros estão de acordo com a atualização

2021-09-28 23:43 UTC, AmandaNbr commented on docs/Versão2-Backlog
> +  |19/08/2021|0.1|Primeira definição de funcionalidades|Pedro Lucas|
Ajustar as versões

2021-09-28 23:44 UTC, AmandaNbr commented on docs/Versão2-Backlog
> +# Referências
Acho que seria bom, pra seguir o padrão dos outros documentos, colocar as referências no final

2021-09-28 23:46 UTC, AmandaNbr requested changes
O documento não está .md, o que dificulta a revisão pois não é possível visualizar em markdown no github

2021-09-29 00:28 UTC, HenriqueHida approved these changes
Bom trabalho! Acredito que a @AmandaNbr destacou todos os possíveis problemas.

2021-09-29 22:35 UTC, AnaCarolinaRodriguesLeite requested changes

2021-09-29 22:35 UTC, AnaCarolinaRodriguesLeite commented on docs/Versão2-Backlog.md
> +|US07|Eu, como usuário, desejo saber sobre as variantes do covid|Must| 3 |
Em vez de 'Eu, como usuário, desejo saber sobre as variantes do covid' troque para = "Eu, como usuário, desejo saber sobre as variantes da covid-19".

2021-09-29 22:35 UTC, AnaCarolinaRodriguesLeite commented on docs/Versão2-Backlog.md
> +|US11|Eu, como usuário, desejo saber sobre os tipos de mascaras|Must| 3 |
A palavra "máscaras" está sem acento.

2021-09-29 22:35 UTC, AnaCarolinaRodriguesLeite commented on docs/Versão2-Backlog.md
> +|US12|Eu, como usuário, desejo saber como usar as mascaras corretamente|Must| 3 |
A palavra "máscaras" está sem acento.

2021-09-29 22:35 UTC, AnaCarolinaRodriguesLeite commented on docs/Versão2-Backlog.md
> +|US41|Eu, como usuário com suspeita de covid, desejo saber oque fazer|Must| 5 |
Depois da palavra saber, a letra 'o' e o 'que' estão juntos.

2021-09-29 22:35 UTC, AnaCarolinaRodriguesLeite commented on docs/Versão2-Backlog.md
> +|US42|Eu, como usuário com suspeita de covid, desejo saber aonde me testar|Should| 5 |
Substituir a palavra 'aonde' por 'onde'.

2021-09-29 22:58 UTC, AmandaNbr approved these changes

2021-10-04 01:30 UTC, AnaCarolinaRodriguesLeite approved these changes

2021-10-04 18:49 UTC, merged