Feature#271/teste rasa
fga-eps-mds/2021-1-Bot pull request #273
Opened 2021-10-03 18:23 UTC by Ericklevy

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [X ] Documentação atualizada
- [X] Novo arquivo 
- [X] Correção de bug 

### Descrição
Foram criados o arquivo.md de teste rasa , resolução de bug e alguns testes de rasa

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #271  | Teste rasa |

## Quem contribuiu?
@Ericklevy 
@DouglasMonteles 
@yudi-azvd

2021-10-03 19:56 UTC, DouglasMonteles reviewed
No arquivo docs/tutoriais/Tutorial_rasa_testes.md existem alguns erros de acentuação e de escrita

2021-10-04 01:06 UTC, yudi-azvd requested changes

2021-10-04 01:06 UTC, yudi-azvd commented on bot/domain.yml
> +        A Alfa tem a mutação que N501Y, que intensifica aligação entre as celulas do virus e humanas
É "aligação" mesmo? Não era pra ser "a ligação"?

Vírus e célula têm acento.

Use "... as células virais e humanas".

2021-10-04 01:06 UTC, yudi-azvd commented on bot/domain.yml
> +        Vacinas como a Janssen e a Pfizer são eficazes contra a Beta, A unica que não funciona e a AstraZeneca
Única tem acento

Não precisa capitalizar o "a" depois da vírgula.

2021-10-04 01:06 UTC, yudi-azvd commented on docs/tutoriais/Tutorial_rasa_testes.md
> +Este e um tutorial que visa a ferramenta do proprio rasa para testar as entradas do usuarios com as respostas do bot.
"Este e um tutorial... " tá faltando acento no "e"

2021-10-04 01:06 UTC, yudi-azvd commented on docs/tutoriais/Tutorial_rasa_testes.md
> +Certifique-se que voce esta na pasta de `bot/tests/` e ir no arquivo `test_stories.yml` .
faltando acento em "está"

2021-10-04 01:06 UTC, yudi-azvd commented on docs/tutoriais/Tutorial_rasa_testes.md
> +Neste `test_stories.yml` crie sua historia e coloque a intenção do usuario `user` insira a frase do usuario e insira as intenções(`intent`) do usuario e as ações(`action`) do bot.
faltando acento em "história", "usuário"

2021-10-04 22:36 UTC, merged