Feature#270/US31
fga-eps-mds/2021-1-Bot pull request #277
Opened 2021-10-05 14:24 UTC by victorear05

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?

- [X] Novo arquivo (mundança que adiciona funcionabilidade)

### Descrição
Foi implementada a US31: "Eu, como usuário, desejo saber como cuidar da minha saúde mental na pandemia".

Close:
| Issue |            Título            |
|-------|:----------------------------:|
| #270 | Implementação da US31 |

## Lista de controle:
- [X] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [X] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [X] Todos os membros estão de acordo com a atualização

## Quem contribuiu?
@victorear05 
@Ericklevy

2021-10-05 20:52 UTC, LamequeFernandes reviewed
Parece tudo certo, mas acho q temos um ou mais conflitos com a main.

2021-10-06 15:14 UTC, victorear05 commented
Conflitos arrumados

2021-10-06 18:26 UTC, klmurussi requested changes

2021-10-06 18:26 UTC, klmurussi commented on bot/domain.yml
> +        Manter a saúde mental nesse tempo de pandemia e quarentena não é uma tarefa nada fácil, se afastar dos seus próximos e se isolar em casa é algo necessário mas muito difícil de se fazer, pois
Erros de português:
"algo necessário, mas"
Não é erro de português, pq n está em pt-br, mas talvez substituir stress por estresse?
"Por isso, aqui vai"

2021-10-06 18:54 UTC, victorear05 commented on bot/domain.yml
> +        Fazer o uso de Álcool, cigarro e outras drogas para lidar com as emoções pode ser atrativo a princípio mas se tornam vícios e, a longo prazo, causam muito malefícios à saúde física e mental.
OK!

2021-10-06 23:52 UTC, klmurussi commented
Falta a estimate tbm antes de fechar.

2021-10-07 13:59 UTC, merged