Feature#323/implementacao das us 45 46
fga-eps-mds/2021-1-Bot pull request #334
Opened 2021-10-18 23:05 UTC by DouglasMonteles

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Nova funcionalidade

@DouglasMonteles 
@kayrocesar

2021-10-19 15:30 UTC, kayrocesar commented
O commit anterior foi desfeito ,pois estava referenciando o PR em vez de referenciar a issue.Também foi desfeito devido a um erro encontrado nas modificações feitas no commit.

2021-10-20 15:26 UTC, Ericklevy approved these changes
Esta muito bom so falta resolver os conflitos que da sucesso

2021-10-20 17:18 UTC, yudi-azvd approved these changes
Parece tudo certo. Bom trabalho. Agora só resolver os conflitos

2021-10-21 20:49 UTC, yudi-azvd requested changes
Parece tudo certo, mas acho que tá faltando os testes

2021-10-22 20:06 UTC, yudi-azvd approved these changes

2021-10-22 20:13 UTC, kayrocesar commented
Alguns warnings foram detectados nos testes e precisam de revisão.



Também foram detectados alguns  erros que provavelmente são provenientes de outras intents não relacionadas ao PR em questão e que provavelmente foram já foram corrigidos na versão atual da main.



![Captura de tela de 2021-10-22 16-43-12](https://user-images.githubusercontent.com/39713656/138516134-dea895d5-adca-4f1b-b2ce-a1623e1e1cc9.png)
![Captura de tela de 2021-10-22 17-05-06](https://user-images.githubusercontent.com/39713656/138516430-5a08024e-049f-47a2-b439-4b5dec9c5ee2.png)
![intent_confusion_matrix](https://user-images.githubusercontent.com/39713656/138517035-687dc2c0-3560-41f9-8ff9-e3e0a543d292.png)


![story_confusion_matrix](https://user-images.githubusercontent.com/39713656/138517055-e2d76e02-18bf-47fb-a7ad-6f9950215791.png)

![intent_histogram](https://user-images.githubusercontent.com/39713656/138517181-e7a18148-87f6-44a2-84cf-c7fc10ad1d0f.png)

2021-10-22 20:41 UTC, yudi-azvd commented
Se voce acha que esse é o caso, faça `git rebase main` na branch dessa PR no seu computador. Aproveita e e já resolve os conflitos se puder.

2021-10-23 17:24 UTC, DouglasMonteles commented
Acabei de subir um commit que remove o warning referente a constrain_similarities, descobrir que tinha que fazer essa alteração no pepiline e não nas politicas

2021-10-24 15:46 UTC, kayrocesar commented
Foram realizados novos testes no bot a partir do ultimo commit  e alguns erros foram detectados .

![photo5163488642386209076](https://user-images.githubusercontent.com/39713656/138601637-a1f41aff-28e4-4731-9c10-b391cb1e49a4.jpg)

2021-10-24 16:42 UTC, DouglasMonteles commented
Foram removidos alguns pepilines que estavam interferindo nos resultados dos testes e que também não erram necessários para a funcionalidade de lembrete

2021-10-24 17:03 UTC, kayrocesar commented
> Foram removidos alguns pepilines que estavam interferindo nos resultados dos testes e que também não erram necessários para a funcionalidade de lembrete

Após a remoção citada,os testes não apresentaram erro:


![Captura de tela de 2021-10-24 13-54-26](https://user-images.githubusercontent.com/39713656/138604641-d4261b8f-9f6d-4a39-b037-b124f7a7655c.png)
![intent_confusion_matrix](https://user-images.githubusercontent.com/39713656/138604698-abee664c-f815-463a-95f6-35972ec12ff1.png)

![story_confusion_matrix](https://user-images.githubusercontent.com/39713656/138604704-d22e1f13-7847-4545-a154-d3b8e7f892ed.png)
![intent_histogram](https://user-images.githubusercontent.com/39713656/138604711-f2f10c41-47f0-4258-98f7-4378d940ae66.png)

2021-10-24 20:03 UTC, merged