:green_heart:(#321) Pipeline de CI/CD
fga-eps-mds/2021-1-Bot pull request #337
Opened 2021-10-19 04:30 UTC by yudi-azvd

## O que mudou?
- [x] Novo arquivo: `pipeline-ci-cd.yml`

### Descrição
Por favor, faça um resumo do que mudou e qual(is) issue(s) foi(ram) resolvida(s). Liste também todas as depedências necessárias para essa mudança.

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #321  | Criar pipeline CI/CD |

      

## Lista de controle:
- [x] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [x] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [x] Todos os membros estão de acordo com a atualização

2021-10-21 20:43 UTC, yudi-azvd commented
@Thais-ra por que remover o comandos pelo `make`?

2021-10-22 15:31 UTC, DouglasMonteles requested changes
Tudo ok, só precisa remover as ultimas duas importações no arquivo `actions.py`, elas já foram importadas na linha 16 & 17.

2021-10-22 15:31 UTC, DouglasMonteles commented on actions/actions.py
> +from .ResponderSobreCovidAction import ResponderSobreCovidAction
Essas ultimas duas importações estão duplicadas

2021-10-22 16:16 UTC, yudi-azvd commented on actions/actions.py
> +from .ResponderSobreCovidAction import ResponderSobreCovidAction
ok, vou resolver

2021-10-24 22:28 UTC, Thais-ra requested changes

2021-10-24 22:28 UTC, Thais-ra commented on .github/workflows/pipeline-ci-cd.yml
> +on:
Não seria melhor colocar o push só pra main? E colocar pra rodar quando derem pull request pra main, pq acho q nao tem necessidade o CI ficar rodando toda vez que alguem der um push em qualquer branch.

2021-10-24 22:37 UTC, yudi-azvd commented on .github/workflows/pipeline-ci-cd.yml
> +on:
Na verdade, só pra `main` não é suficiente. O linter, por exemplo, tem que ser rodado em toda branch, assim como os testes também.

2021-10-24 23:54 UTC, DouglasMonteles approved these changes

2021-10-26 17:05 UTC, Thais-ra approved these changes

2021-10-26 17:06 UTC, merged