Feature#330/humanizacao1-10
fga-eps-mds/2021-1-Bot pull request #350
Opened 2021-10-20 16:21 UTC by PedroLSF

## O que mudou?
Falas mais humanizadas, adição de fontes e por fim algumas intent's adicionadas

### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Mudança na estrutura do código

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #330  | Humanização de US's que não precisam de link |
| #343  | Avaliação e Humanização das issues que necessitam de links |

2021-10-20 18:00 UTC, gatotabaco requested changes
Aqui estão algumas mudanças que eu achei fundamentais no seu trabalho. No geral foi de altíssima qualidade e gostei muito... parabéns pelas reformulações de frase que não fizeram cair a qualidade da informação.

2021-10-21 14:46 UTC, AnaCarolinaRodriguesLeite requested changes
Parabéns pelo excelente trabalho! A linguagem ficou muito mais atrativamente informal e até mesmo divertida.

2021-10-21 18:36 UTC, gatotabaco approved these changes

2021-10-21 23:40 UTC, AnaCarolinaRodriguesLeite approved these changes

2021-10-21 23:41 UTC, merged