Humanização e revisão das US 22 a 31
fga-eps-mds/2021-1-Bot pull request #352
Opened 2021-10-20 20:32 UTC by HenriqueHida

## O que mudou?
Revisão, humanização e adição das fontes nas US 22 até a 31

### Qual foi a mudança significativa para que haja um Pull Request?
- [ ] Documentação atualizada

### Descrição
Alteração das US 22 a 31, adicionando personalidade ao bot e as fontes de cada US.

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #344 | Humanização e revisão das US 22 até 31 |

2021-10-21 00:35 UTC, klmurussi commented
Mt bom

2021-10-21 14:32 UTC, AnaCarolinaRodriguesLeite requested changes

2021-10-21 19:02 UTC, gatotabaco requested changes
Parabéns pelo trabalho. Adicionei alguns tópicos que considerei relevantes para a melhora na qualidade.

Além disso, se possível, busque utilizar mais emojis!

2021-10-22 12:09 UTC, gatotabaco approved these changes

2021-10-22 17:44 UTC, merged