Feature#348/us33
fga-eps-mds/2021-1-Bot pull request #354
Opened 2021-10-20 22:40 UTC by DouglasMonteles

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [ ] Nova funcionalidade referente a US 33

@DouglasMonteles

2021-10-20 23:26 UTC, Ericklevy approved these changes
muito bom

2021-10-21 00:26 UTC, klmurussi commented
muito bom @Ericklevy , só falta vc colocar sua estimate na issue

2021-10-21 20:46 UTC, yudi-azvd requested changes
Parece tudo certo, mas não está faltando testes? aqueles no arquivo `test_stories.yml`

2021-10-23 22:40 UTC, DouglasMonteles commented
Teste adicionado, se você puder verificar @yudi-azvd

2021-10-24 22:33 UTC, yudi-azvd requested changes

2021-10-24 22:33 UTC, yudi-azvd commented on actions/actions.py
> +
Use sintaxe

```py
from modulo.submodulo import classe
# 
from actions.ResponderQuantidadeVacinados import ResponderQuantidadeVacinados
```

2021-10-24 23:20 UTC, yudi-azvd approved these changes

2021-10-24 23:21 UTC, merged