Feature#356/testes us21 26
fga-eps-mds/2021-1-Bot pull request #374
Opened 2021-10-23 02:16 UTC by klmurussi

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Mudança decisiva no arquivo (correção ou recurso que faz com que funcionabilidade existente seja alterada)

### Descrição
Testes das US21-16

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #356 | Realizar testes nas US21-26 |
      

## Lista de controle:
- [X] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [X] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [x] Todos os membros estão de acordo com a atualização

## Quem contribuiu?
@klmurussi

2021-10-23 15:13 UTC, Ericklevy requested changes
o arquivo .example .env não pode deixar as credencias sempre coloque no env que tem git ignore ae depois disso fica mais safe e podera merga

2021-10-23 15:21 UTC, yudi-azvd requested changes

2021-10-23 15:21 UTC, yudi-azvd commented on .example.env
> +BOT_URL=https://alligabot.herokuapp.com/
É melhor apagar esse commit da história do git pq se não as credenciais vão ficar expostas pra todo mundo.

Como o Erick disse, as credenciais vão no arquivo `.env`. O arquivo `.example.env` é um template e não deve ser alterado

Resolvendo isso e os conflitos tá tudo certo

2021-10-24 00:04 UTC, klmurussi commented on .example.env
> +BOT_URL=https://alligabot.herokuapp.com/
prontinho

2021-10-24 21:44 UTC, Ericklevy approved these changes
Código concertado tudo certo pode mergar

2021-10-24 23:22 UTC, yudi-azvd requested changes

2021-10-24 23:22 UTC, yudi-azvd commented on .example.env
> +BOT_URL = https: // url-do-seu-servidor. com
Não precisa desses espaços adicionais. Pode deixar como estava 😃

2021-10-25 04:12 UTC, Ericklevy requested changes
Arruma so o env que esta sucesso

2021-10-25 17:49 UTC, yudi-azvd approved these changes

2021-10-25 19:17 UTC, Ericklevy approved these changes
Pode dar o merge

2021-10-25 19:20 UTC, merged