Feature#367/Testes rasa da  US16 até a US20 e alteração de intent
fga-eps-mds/2021-1-Bot pull request #375
Opened 2021-10-23 16:58 UTC by kayrocesar

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?

- [x] Mudança decisiva no arquivo (correção ou recurso que faz com que funcionabilidade existente seja alterada)

### Descrição
Testes rasa nas US 16 até 20 e alteração na intent da US 14,pois a US 14 e 16 se tornaram uma só.

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #367  | Testes rasa da  US16 até a US20 |

      

## Lista de controle:
- [x] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [x] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [x] Todos os membros estão de acordo com a atualização

## Quem contribuiu?
@kayrocesar

2021-10-23 22:57 UTC, DouglasMonteles requested changes
Tudo certo, só precisa resolver as duplicações

2021-10-23 22:57 UTC, DouglasMonteles commented on bot/data/stories.yml
> +- story: Informando ao usuário a quantidade de infectados de infectados e mortos por cidade
Apagar um dos "de infectados" na linha 138, que está duplicado

2021-10-23 22:57 UTC, DouglasMonteles commented on bot/tests/test_stories.yml
> +- story:  Informando ao usuário a quantidade de infectados de infectados e mortos por cidade
Aqui a mesma coisa, "de infectados" está repetido

2021-10-24 03:34 UTC, kayrocesar commented on bot/data/stories.yml
> +- story: Informando ao usuário a quantidade de infectados de infectados e mortos por cidade
Problema corrigido.

2021-10-24 03:34 UTC, kayrocesar commented on bot/tests/test_stories.yml
> +- story:  Informando ao usuário a quantidade de infectados de infectados e mortos por cidade
Problema corrigido.

2021-10-24 21:47 UTC, DouglasMonteles approved these changes
Tudo certo

2021-10-25 02:49 UTC, LamequeFernandes approved these changes
Tudo certo.

2021-10-25 03:45 UTC, merged