Documentation#365/alteraçao backlog
fga-eps-mds/2021-1-Bot pull request #382
Opened 2021-10-25 00:49 UTC by Thais-ra

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Documentação atualizada

### Descrição
Adição no backlog de uma tabela indicando quais US não foram feitas.
Exclusão da US06, US16 e US47 e alteração da US02 e US14

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #365 | Alteração no documento de backlog |

2021-10-25 02:48 UTC, AmandaNbr requested changes

2021-10-25 02:48 UTC, AmandaNbr commented on docs/_posts/2021-08-13-backlog.md
>  #### FT03: Transmissão e prevenção
Como a FT02 foi apagada, essa seria a FT02 e assim em diante

2021-10-25 02:48 UTC, AmandaNbr commented on docs/_posts/2021-08-13-backlog.md
> +|US15|Eu, como usuário, desejo saber os cuidados que devo ter em locais abertos|Must| 3 |
Essa US seria a 16

2021-10-25 20:45 UTC, gatotabaco requested changes

2021-10-25 20:45 UTC, gatotabaco commented on docs/_posts/2021-08-13-backlog.md
>  #### FT03: Transmissão e prevenção
Concordo. Tem que corrigir as numeraçoes.

2021-10-25 20:45 UTC, gatotabaco commented on docs/_posts/2021-08-13-backlog.md
>  #### FT04: Regras para lugares específicos
corrigir FT

2021-10-25 20:45 UTC, gatotabaco commented on docs/_posts/2021-08-13-backlog.md
>  #### FT05: Como continuar trabalhando de maneira segura
Corrigir FT

2021-10-25 20:45 UTC, gatotabaco commented on docs/_posts/2021-08-13-backlog.md
>  #### FT06: Preciso pegar transporte público
Corrigir FT

2021-10-25 20:45 UTC, gatotabaco commented on docs/_posts/2021-08-13-backlog.md
>  #### FT07: Home office e saúde mental
Corrigir FT

2021-10-25 20:45 UTC, gatotabaco commented on docs/_posts/2021-08-13-backlog.md
>  #### FT08: Vacinação
Corrigir FT

2021-10-25 20:45 UTC, gatotabaco commented on docs/_posts/2021-08-13-backlog.md
>  #### FT09: Detecção
Corrigir a FT

2021-10-25 21:05 UTC, Thais-ra commented on docs/_posts/2021-08-13-backlog.md
>  #### FT03: Transmissão e prevenção
Nossa, verdade, deixei passar completamente

2021-10-26 00:34 UTC, AmandaNbr requested changes

2021-10-26 00:34 UTC, AmandaNbr commented on docs/_posts/2021-08-13-backlog.md
> +
Ficou faltando a US: "Eu, como usuário, desejo ser lembrado da próxima dose da vacina" após a US 44

2021-10-26 02:55 UTC, gatotabaco requested changes

2021-10-26 02:55 UTC, gatotabaco commented on docs/_posts/2021-08-13-backlog.md
> +
concordo

2021-10-26 14:05 UTC, AmandaNbr requested changes
Atualizar o número das us não feitas

2021-10-26 14:12 UTC, AmandaNbr approved these changes

2021-10-26 17:50 UTC, gatotabaco approved these changes

2021-10-26 17:58 UTC, AmandaNbr requested changes
Estava certo antes (':

2021-10-26 18:45 UTC, AmandaNbr approved these changes

2021-10-26 18:47 UTC, merged